In [1]:
import numpy as np
import pandas as pd

In [7]:
df = pd.read_csv("/Users/Prashant/Downloads/social_media.csv")

In [8]:
df.head()

,User_ID,Age,Gender,Occupation,Relationship_Status,Primary_Platform,Daily_Usage_Hours,Platforms_Used_Count,Posts_Per_Week,Late_Night_Usage,...,Loneliness_Score,Self_Esteem_Score,Sleep_Quality_Score,Sleep_Hours,Productivity_Loss_Score,Offline_Relationship_Quality,Physical_Activity_Hrs_Week,Screen_Free_Time_Hrs,Mental_Wellbeing_Score,Addiction_Level
0,USR00001,30,Male,Working Professional,In a Relationship,YouTube,2.9,4,3,No,...,1.7,6.5,8.5,5.3,3.7,3.8,5.8,3.1,7.3,Low
1,USR00002,19,Male,Student,Married,Instagram,4.8,1,0,NaN,...,7.0,7.5,7.8,5.5,4.0,1.8,0.9,3.3,4.1,Severe
2,USR00003,40,Male,Student,In a Relationship,YouTube,NaN,4,5,No,...,5.6,5.3,6.3,NaN,5.8,2.8,0.0,1.5,5.6,High
3,USR00004,37,Female,Student,Married,Facebook,7.7,2,3,Yes,...,5.6,1.4,3.9,6.1,5.5,3.6,1.0,3.9,4.3,Severe
4,USR00005,18,Non-binary,Student,In a Relationship,TikTok,4.6,3,0,No,...,4.0,NaN,5.7,5.0,3.8,3.2,0.6,1.0,6.6,Moderate

In [10]:
df.tail()

,User_ID,Age,Gender,Occupation,Relationship_Status,Primary_Platform,Daily_Usage_Hours,Platforms_Used_Count,Posts_Per_Week,Late_Night_Usage,...,Loneliness_Score,Self_Esteem_Score,Sleep_Quality_Score,Sleep_Hours,Productivity_Loss_Score,Offline_Relationship_Quality,Physical_Activity_Hrs_Week,Screen_Free_Time_Hrs,Mental_Wellbeing_Score,Addiction_Level
1495,USR01496,40,Male,Working Professional,In a Relationship,TikTok,2.7,2,4,No,...,3.3,7.4,8.5,6.7,4.5,7.6,2.3,2.3,6.5,High
1496,USR01497,23,Non-binary,Student,Married,YouTube,3.5,3,6,Yes,...,4.2,1.9,7.2,6.9,7.2,NaN,2.8,2.0,6.4,Moderate
1497,USR01498,39,Female,Student,Single,Instagram,5.3,2,3,Yes,...,0.4,2.4,5.1,NaN,6.4,7.8,2.6,4.8,4.7,Severe
1498,USR01499,26,Female,Freelancer,Single,Twitter/X,7.3,4,0,Yes,...,7.5,6.6,6.4,4.2,9.1,6.4,3.6,2.1,6.4,High
1499,USR01500,16,Female,Working Professional,In a Relationship,TikTok,0.7,3,2,No,...,5.9,8.5,5.3,7.2,3.4,2.3,3.9,3.1,6.1,Moderate